version: '3.8'

services:
  usuarios-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ana
      MYSQL_DATABASE: usuarios_db
    volumes:
      - usuarios-db-data:/var/lib/mysql
    networks:
      - biblioteca-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  libros-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ana
      MYSQL_DATABASE: libros_db
    volumes:
      - libros-db-data:/var/lib/mysql
    networks:
      - biblioteca-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  prestamos-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ana
      MYSQL_DATABASE: prestamos_db
    volumes:
      - prestamos-db-data:/var/lib/mysql
    networks:
      - biblioteca-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  usuarios:
    image: anamarirvera/biblioteca-usuarios
    environment:
      DB_HOST: usuarios-db
      DB_PASSWORD: ana
      DB_NAME: usuarios_db
    networks:
      - biblioteca-net
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker

  libros:
    image: anamarirvera/biblioteca-libros
    environment:
      DB_HOST: libros-db
      DB_PASSWORD: ana
      DB_NAME: libros_db
    networks:
      - biblioteca-net
    ports:
      - target: 3002
        published: 3002
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker

  prestamos:
    image: anamarirvera/biblioteca-prestamos
    environment:
      DB_HOST: prestamos-db
      DB_PASSWORD: ana
      DB_NAME: prestamos_db
    networks:
      - biblioteca-net
    ports:
      - target: 3003
        published: 3003
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker

networks:
  biblioteca-net:
    driver: overlay
    attachable: true

volumes:
  usuarios-db-data:
  libros-db-data:
  prestamos-db-data:
